-- fff.nvim: file finding and live grep.
--
-- Takes over the two pickers that dominate use here. Both were telescope +
-- rg-per-keystroke; fff keeps a Rust index of the tree in-process and greps it
-- with a wall-clock budget, so neither one respawns a process per character.
-- Everything telescope does that fff has no equivalent for (buffers, oldfiles,
-- git, LSP/ctags symbols, the gitignored-files escape hatch) stays on
-- telescope -- see the header of config/telescope.lua.
--
-- Query syntax replaces two hand-rolled telescope keymaps: `*.rs`, `src/**/*.c`
-- and `!test/` are understood by find AND grep, which is what <leader>fg's
-- "search --- *.ext" prompt and <leader>/'s `**file` on_input_filter_cb were
-- reimplementing. <S-Tab> cycles plain/regex/fuzzy inside the picker.

local M = {}

local search_root = require("utils.project_root").search_root
local skip_dirs = require("utils.skip_dirs")

local JAI_MODULES = "/Users/alexmatthewcandelario/gits/jai/modules"

---Picker options scoped to the project root, titled after it.
---@param prefix string
---@return table
local function in_root(prefix)
    local root = search_root()
    return { cwd = root, title = prefix .. " in " .. vim.fn.fnamemodify(root, ":t") }
end

-- fff has no exclude-list config: the walker indexes what it reaches, honouring
-- .gitignore and .ignore and nothing else. The vendored trees skipped
-- everywhere else in this config (utils.skip_dirs) are CHECKED IN, so
-- .gitignore does not filter them -- the 1060ms-per-keystroke measurements in
-- config/telescope.lua are what that costs. :FFFIgnore writes the equivalent
-- .ignore at the project root.
--
-- Opt-in per project, like :ClangdSetup, because it puts a file in the repo --
-- and because rg and fd honour .ignore too, so external/ disappears from shell
-- greps in that tree as well.
local IGNORE_HEADER = "# generated by :FFFIgnore -- delete this line to keep hand edits"

local function write_ignore()
    local root = search_root()
    local path = root .. "/.ignore"

    local existing = io.open(path, "r")
    if existing then
        local first = existing:read("l")
        existing:close()
        if first ~= IGNORE_HEADER then
            vim.notify(path .. " was not generated here; leaving it alone", vim.log.levels.WARN)
            return
        end
    end

    local lines = { IGNORE_HEADER }
    for _, dir in ipairs(skip_dirs.NAMES) do
        lines[#lines + 1] = dir .. "/"
    end
    -- The entries fff needs on top of the shared list, same three telescope
    -- adds: external/ is deliberately out of skip_dirs (clangd_setup and ctags
    -- look inside it for real include dirs), .cache/ holds clangd's binary
    -- background index, and *.dSYM/ is never worth grepping.
    vim.list_extend(lines, { "external/", ".cache/", "*.dSYM/" })

    vim.fn.writefile(lines, path)
    vim.notify("wrote " .. path .. " -- run :FFFScan to reindex")
end

function M.setup()
    -- Read lazily by fff.conf on first picker open, so this costs nothing at
    -- startup and no fff module is required here.
    --
    -- lazy_sync must be EXPLICITLY true: plugin/fff.lua reads vim.g.fff.lazy_sync
    -- directly and indexes at UIEnter when it is nil, which is the opposite of
    -- what the name suggests.
    vim.g.fff = {
        lazy_sync = true,
        prompt = "> ",
        layout = {
            width = 0.8,
            height = 0.8,
            prompt_position = "bottom",
            preview_position = "top",
            preview_size = 0.4,
        },
        keymaps = {
            move_down = { "<Down>", "<C-n>", "<C-j>" },
            move_up = { "<Up>", "<C-p>", "<C-k>" },
        },
        grep = {
            -- Matches telescope's --max-filesize=1M. Nothing hand-written here
            -- comes close; the generated headers this codebase has a lot of do
            -- (a 63MB slang-core-module-generated.h) and are pure noise.
            max_file_size = 1024 * 1024,
        },
    }

    vim.api.nvim_create_user_command("FFFIgnore", write_ignore, {
        desc = "Write a .ignore at the project root from utils.skip_dirs",
    })

    vim.keymap.set("n", "<leader>ff", function()
        require("fff").find_files(in_root("Files"))
    end, { desc = "Find files" })

    vim.keymap.set("n", "<leader>/", function()
        require("fff").live_grep(in_root("Grep"))
    end, { desc = "Live grep (project root)" })

    vim.keymap.set("n", "<leader>.", function()
        local cwd = vim.fn.getcwd()
        require("fff").live_grep({
            cwd = cwd,
            title = "Grep in " .. vim.fn.fnamemodify(cwd, ":t"),
        })
    end, { desc = "Live grep (current dir)" })

    -- One entry point for "grep what I'm looking at": live_grep_under_cursor
    -- takes <cword> in normal mode and the selection in visual.
    vim.keymap.set({ "n", "v" }, "<leader>pws", function()
        require("fff").live_grep_under_cursor(in_root("Grep"))
    end, { desc = "Grep word under cursor / selection" })

    vim.keymap.set("n", "<leader>pWs", function()
        local opts = in_root("Grep")
        opts.query = vim.fn.expand("<cWORD>")
        require("fff").live_grep(opts)
    end, { desc = "Grep WORD under cursor" })

    vim.keymap.set("n", "<leader>fr", function()
        require("fff").resume()
    end, { desc = "Resume last picker" })

    vim.keymap.set("n", "<leader>jg", function()
        require("fff").live_grep({ cwd = JAI_MODULES, title = "Grep Jai Modules" })
    end, { desc = "Grep search in Jai modules" })

    vim.keymap.set("n", "<leader>js", function()
        local patterns = {
            ["All Symbols"] = "",
            ["Functions (::)"] = "\\w+\\s*::",
            ["Structs"] = "struct\\s+\\w+",
            ["Enums"] = "enum\\s+\\w+",
            ["Constants"] = "^\\s*\\w+\\s*::\\s*:",
        }
        vim.ui.select(
            { "All Symbols", "Functions (::)", "Structs", "Enums", "Constants" },
            { prompt = "Select symbol type to search:" },
            function(choice)
                if not choice then return end
                require("fff").live_grep({
                    cwd = JAI_MODULES,
                    title = "Jai " .. choice,
                    query = patterns[choice],
                    -- The prefilled patterns are regex, so open in regex mode
                    -- rather than making the first <S-Tab> mandatory.
                    grep = { modes = { "regex", "plain", "fuzzy" } },
                })
            end
        )
    end, { desc = "Search Jai module symbols" })
end

return M
