-- fff finds files and greps. Everything else is native: a command with fuzzy
-- cmdline completion (config/options.lua) to pick a name, quickfix or the
-- location list for locations.
local project = require('config.project')

local M = {}

local JAI_MODULES = vim.fs.normalize('~/gits/jai/modules')

-- Skipped on top of .gitignore. external/ is not in SKIP_DIRS because clangd
-- and ctags look inside it for include dirs; .cache/ holds clangd's index.
local IGNORED = vim.list_extend(vim.deepcopy(project.SKIP_DIRS), { 'external', '.cache', '*.dSYM' })
local IGNORE_HEADER = '# generated by :FFFIgnore, delete this line to keep hand edits'

local function in_root(title)
  local root = project.search_root()
  return { cwd = root, title = title .. ' in ' .. vim.fs.basename(root) }
end

-- fff only honours .gitignore and .ignore, and vendored trees are checked in.
local function write_ignore()
  local path = project.search_root() .. '/.ignore'
  if vim.uv.fs_stat(path) and vim.fn.readfile(path, '', 1)[1] ~= IGNORE_HEADER then
    vim.notify(path .. ' was not generated here; leaving it alone', vim.log.levels.WARN)
    return
  end
  local lines = { IGNORE_HEADER }
  for _, dir in ipairs(IGNORED) do
    lines[#lines + 1] = dir .. '/'
  end
  vim.fn.writefile(lines, path)
  vim.notify('wrote ' .. path .. ', run :FFFScan to reindex')
end

local function jai_symbols()
  local patterns = {
    { 'All Symbols', '' },
    { 'Functions (::)', [[\w+\s*::]] },
    { 'Structs', [[struct\s+\w+]] },
    { 'Enums', [[enum\s+\w+]] },
    { 'Constants', [[^\s*\w+\s*::\s*:]] },
  }
  vim.ui.select(patterns, {
    prompt = 'Select symbol type to search:',
    format_item = function(p) return p[1] end,
  }, function(choice)
    if choice then
      require('fff').live_grep({
        cwd = JAI_MODULES,
        title = 'Jai ' .. choice[1],
        query = choice[2],
        grep = { modes = { 'regex', 'plain', 'fuzzy' } },
      })
    end
  end)
end

-- Listed buffers by last use, then v:oldfiles, under cwd.
local function recent_files()
  local cwd = vim.fn.getcwd() .. '/'
  local bufs = vim.fn.getbufinfo({ buflisted = 1 })
  table.sort(bufs, function(a, b) return a.lastused > b.lastused end)
  local paths = vim.tbl_map(function(b) return b.name end, bufs)
  vim.list_extend(paths, vim.v.oldfiles)
  local files, seen = {}, {}
  for _, path in ipairs(paths) do
    if not seen[path] and vim.startswith(path, cwd) and vim.uv.fs_stat(path) then
      seen[path] = true
      files[#files + 1] = path:sub(#cwd + 1)
    end
  end
  return files
end

local function git(args)
  local root = project.search_root()
  return vim.system(vim.list_extend({ 'git' }, args), { cwd = root, text = true }):wait(), root
end

-- Local branches, plus remote ones by their short name so `git switch` creates the tracking branch.
local function branches()
  local names, seen = {}, {}
  local res = git({ 'branch', '--all', '--format=%(refname)' })
  for ref in (res.stdout or ''):gmatch('[^\n]+') do
    local name = ref:match('^refs/heads/(.+)') or ref:match('^refs/remotes/[^/]+/(.+)')
    if name and name ~= 'HEAD' and not seen[name] then
      seen[name] = true
      names[#names + 1] = name
    end
  end
  return names
end

local function git_status()
  local res, root = git({ 'status', '--porcelain', '-z' })
  if res.code ~= 0 then return vim.notify(vim.trim(res.stderr), vim.log.levels.ERROR) end
  local entries = vim.split(res.stdout, '\0', { trimempty = true })
  local items = {}
  local i = 1
  while i <= #entries do
    local status = entries[i]:sub(1, 2)
    items[#items + 1] = { filename = root .. '/' .. entries[i]:sub(4), lnum = 1, text = status }
    -- A rename or copy is followed by its source path.
    i = i + (status:match('[RC]') and 2 or 1)
  end
  vim.fn.setqflist({}, ' ', { title = 'git status', items = items })
  vim.cmd('botright copen')
end

local function git_buffer(args)
  local res = git(args)
  if res.code ~= 0 then return vim.notify(vim.trim(res.stderr), vim.log.levels.ERROR) end
  vim.cmd('botright new')
  local buf = vim.api.nvim_get_current_buf()
  vim.bo[buf].buftype = 'nofile'
  vim.bo[buf].bufhidden = 'wipe'
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.split(res.stdout, '\n', { trimempty = true }))
  vim.bo[buf].modifiable = false
  vim.bo[buf].filetype = 'git'
  vim.keymap.set('n', 'q', '<cmd>close<CR>', { buf = buf })
  return buf
end

local function git_log()
  local buf = git_buffer({ 'log', '--oneline', '--decorate', '-n', '1000' })
  if buf then
    vim.keymap.set('n', '<CR>', function()
      git_buffer({ 'show', vim.api.nvim_get_current_line():match('^%x+') })
    end, { buf = buf, desc = 'Show commit' })
  end
end

local function has_lsp()
  return next(vim.lsp.get_clients({ bufnr = 0 })) ~= nil
end

-- Without an LSP, ctags over this one file.
local function document_symbols()
  if has_lsp() then return vim.lsp.buf.document_symbol() end
  local file = vim.api.nvim_buf_get_name(0)
  local res = vim.system({ 'ctags', '-f', '-', '--sort=no', '--fields=+nK', file }, { text = true }):wait()
  local items = {}
  for line in (res.stdout or ''):gmatch('[^\n]+') do
    local name, kind, lnum = line:match('^([^\t]+)\t.*;"\t([^\t]+)\tline:(%d+)')
    if name then
      items[#items + 1] = { filename = file, lnum = tonumber(lnum), text = kind .. ' ' .. name }
    end
  end
  vim.fn.setloclist(0, {}, ' ', { title = 'Symbols', items = items })
  vim.cmd('lopen')
end

local function workspace_symbols()
  if has_lsp() then return vim.lsp.buf.workspace_symbol() end
  vim.api.nvim_feedkeys(':tag ', 'n', false)
end

function M.setup()
  -- lazy_sync must be explicitly true, or fff indexes getcwd() at UIEnter
  -- instead of the root the UIEnter hook below picks.
  vim.g.fff = {
    lazy_sync = true,
    prompt = '> ',
    layout = { width = 0.8, height = 0.8, prompt_position = 'bottom', preview_position = 'top', preview_size = 0.4 },
    keymaps = { move_down = { '<Down>', '<C-n>', '<C-j>' }, move_up = { '<Up>', '<C-p>', '<C-k>' } },
    grep = { max_file_size = 1024 * 1024 },
  }

  -- Index right after startup, so the first picker does not open on a cold
  -- scan. Home is skipped: indexing it would walk all of ~.
  vim.api.nvim_create_autocmd('UIEnter', {
    once = true,
    callback = vim.schedule_wrap(function()
      local root = project.search_root()
      if root == vim.fs.normalize('~') then return end
      vim.g.fff = vim.tbl_extend('force', vim.g.fff, { base_path = root })
      require('fff.core').ensure_initialized()
      require('fff.picker_ui.picker_ui')
    end),
  })

  local globs = { "'--glob=!.git/'" }
  for _, dir in ipairs(IGNORED) do
    globs[#globs + 1] = ("'--glob=!**/%s/**'"):format(dir)
  end
  vim.o.grepprg = 'rg --vimgrep --smart-case --hidden --no-ignore-vcs --max-filesize=1M ' .. table.concat(globs, ' ')

  local cmd = vim.api.nvim_create_user_command
  cmd('FFFIgnore', write_ignore, { desc = 'Write a .ignore at the project root' })
  -- The escape hatch: fff never indexes gitignored files, :Grep does.
  cmd('Grep', function(o)
    vim.cmd('silent grep! ' .. o.args .. ' ' .. vim.fn.fnameescape(project.search_root()))
    vim.cmd('botright cwindow')
  end, { nargs = '+', desc = 'rg into quickfix, including gitignored files' })
  cmd('Recent', function(o) vim.cmd.edit(o.args) end, {
    nargs = 1,
    complete = function(arg)
      local files = recent_files()
      return arg == '' and files or vim.fn.matchfuzzy(files, arg)
    end,
    desc = 'Edit a recent file under cwd',
  })
  cmd('Branch', function(o)
    -- git switch reports on stderr whether it succeeds or not.
    local res = git({ 'switch', o.args })
    vim.notify(vim.trim(res.stderr), res.code == 0 and vim.log.levels.INFO or vim.log.levels.ERROR)
    if res.code == 0 then vim.cmd.checktime() end
  end, {
    nargs = 1,
    complete = function(arg)
      local names = branches()
      return arg == '' and names or vim.fn.matchfuzzy(names, arg)
    end,
    desc = 'Switch git branch',
  })

  local map = vim.keymap.set
  map('n', '<leader>ff', function() require('fff').find_files(in_root('Files')) end, { desc = 'Find files' })
  map('n', '<leader>/', function() require('fff').live_grep(in_root('Grep')) end, { desc = 'Grep project' })
  map('n', '<leader>.', function()
    local cwd = vim.fn.getcwd()
    require('fff').live_grep({ cwd = cwd, title = 'Grep in ' .. vim.fs.basename(cwd) })
  end, { desc = 'Grep cwd' })
  map({ 'n', 'v' }, '<leader>pws', function()
    require('fff').live_grep_under_cursor(in_root('Grep'))
  end, { desc = 'Grep word under cursor / selection' })
  map('n', '<leader>pWs', function()
    local opts = in_root('Grep')
    opts.query = vim.fn.expand('<cWORD>')
    require('fff').live_grep(opts)
  end, { desc = 'Grep WORD under cursor' })
  map('n', '<leader>fr', function() require('fff').resume() end, { desc = 'Resume last picker' })
  map('n', '<leader>jg', function()
    require('fff').live_grep({ cwd = JAI_MODULES, title = 'Grep Jai Modules' })
  end, { desc = 'Grep Jai modules' })
  map('n', '<leader>js', jai_symbols, { desc = 'Search Jai module symbols' })

  map('n', '<leader>fb', ':b ', { desc = 'Buffers' })
  map('n', '<leader>fo', ':Recent ', { desc = 'Recent files under cwd' })
  map('n', '<leader>pg', ':Grep ', { desc = 'Grep including gitignored files' })
  map('n', '<leader>ds', document_symbols, { desc = 'Document symbols' })
  map('n', '<leader>ws', workspace_symbols, { desc = 'Workspace symbols' })
  map('n', '<leader>gs', git_status, { desc = 'Git status' })
  map('n', '<leader>gc', git_log, { desc = 'Git log' })
  map('n', '<leader>gb', ':Branch ', { desc = 'Switch git branch' })
end

return M
