-- Aether colorscheme for Neovim
local colors = {
    -- Monotone shades (base00-base07)
    base00 = "#0f0f0f", -- Default background
    base01 = "#5e5959", -- Lighter background (status bars)
    base02 = "#2a2525", -- Selection background
    base03 = "#5e5959", -- Comments, invisibles
    base04 = "#e6caab", -- Dark foreground
    base05 = "#eadccc", -- Default foreground
    base06 = "#eadccc", -- Light foreground
    base07 = "#e6caab", -- Light background

    -- Accent colors (base08-base0F)
    base08 = "#e25d6c", -- Variables, errors, red
    base09 = "#e9838f", -- Integers, constants, orange
    base0A = "#f4bb54", -- Classes, types, yellow
    base0B = "#cea37f", -- Strings, green
    base0C = "#e8ab3b", -- Support, regex, cyan
    base0D = "#e2be8a", -- Functions, keywords, blue
    base0E = "#f66151", -- Keywords, storage, magenta
    base0F = "#edb95a", -- Deprecated, brown/yellow
}

colors.none = "NONE"

vim.cmd("highlight clear")
vim.o.background = "dark"
vim.g.colors_name = "aether"

local set = vim.api.nvim_set_hl

-- Core UI
set(0, "Normal", { fg = colors.base05, bg = colors.base00 })
set(0, "NormalNC", { fg = colors.base05, bg = colors.base00 })
set(0, "NormalFloat", { fg = colors.base05, bg = colors.base01 })
set(0, "FloatBorder", { fg = colors.base03, bg = colors.base01 })
set(0, "FloatTitle", { fg = colors.base0D, bg = colors.base01 })
set(0, "WinSeparator", { fg = colors.base01 })
set(0, "VertSplit", { fg = colors.base01 })
set(0, "StatusLine", { fg = colors.base00, bg = colors.base05 })
set(0, "StatusLineNC", { fg = colors.base03, bg = colors.base01 })
set(0, "TabLine", { fg = colors.base03, bg = colors.base01 })
set(0, "TabLineSel", { fg = colors.base00, bg = colors.base05 })
set(0, "TabLineFill", { fg = colors.base03, bg = colors.base00 })
set(0, "LineNr", { fg = colors.base03, bg = colors.base00 })
set(0, "CursorLineNr", { fg = colors.base05, bg = colors.base00 })
set(0, "SignColumn", { fg = colors.base03, bg = colors.base00 })
set(0, "CursorColumn", { bg = colors.base01 })
set(0, "CursorLine", { bg = colors.base01 })
set(0, "Cursor", { fg = colors.base00, bg = colors.base05 })
set(0, "TermCursor", { fg = colors.base00, bg = colors.base05 })
set(0, "TermCursorNC", { fg = colors.base00, bg = colors.base03 })
set(0, "Visual", { bg = colors.base02 })
set(0, "VisualNOS", { bg = colors.base02 })
set(0, "Search", { fg = colors.base00, bg = colors.base0A })
set(0, "IncSearch", { fg = colors.base00, bg = colors.base09 })
set(0, "CurSearch", { fg = colors.base00, bg = colors.base09 })
set(0, "Substitute", { link = "IncSearch" })
set(0, "MatchParen", { fg = colors.base00, bg = colors.base0D, bold = true })
set(0, "ColorColumn", { bg = colors.base01 })
set(0, "Folded", { fg = colors.base03, bg = colors.base01 })
set(0, "FoldColumn", { fg = colors.base03, bg = colors.base00 })
set(0, "EndOfBuffer", { fg = colors.base00 })
set(0, "NonText", { fg = colors.base03 })
set(0, "Whitespace", { fg = colors.base02 })
set(0, "SpecialKey", { fg = colors.base03 })
set(0, "QuickFixLine", { fg = colors.base05, bg = colors.base01 })
set(0, "qfLineNr", { fg = colors.base0A })
set(0, "Directory", { fg = colors.base0D })
set(0, "Title", { fg = colors.base0D, bold = true })
set(0, "Question", { fg = colors.base0B })
set(0, "MoreMsg", { fg = colors.base0B })
set(0, "ModeMsg", { fg = colors.base05 })
set(0, "WarningMsg", { fg = colors.base09 })
set(0, "ErrorMsg", { fg = colors.base08 })
set(0, "Pmenu", { fg = colors.base05, bg = colors.base01 })
set(0, "PmenuSel", { fg = colors.base00, bg = colors.base0D })
set(0, "PmenuSbar", { bg = colors.base01 })
set(0, "PmenuThumb", { bg = colors.base03 })
set(0, "WildMenu", { fg = colors.base00, bg = colors.base0D })
set(0, "CursorLineFold", { bg = colors.base01 })
set(0, "CursorLineSign", { bg = colors.base01 })
set(0, "WinBar", { fg = colors.base05, bg = colors.base00 })
set(0, "WinBarNC", { fg = colors.base03, bg = colors.base00 })

-- Syntax
set(0, "Comment", { fg = colors.base03, italic = false })
set(0, "SpecialComment", { fg = colors.base03 })
set(0, "Todo", { fg = colors.base0A, bg = colors.base01, bold = true })
set(0, "String", { fg = colors.base0B })
set(0, "Character", { fg = colors.base0B })
set(0, "Number", { fg = colors.base09 })
set(0, "Float", { fg = colors.base09 })
set(0, "Boolean", { fg = colors.base09 })
set(0, "Constant", { fg = colors.base09 })
set(0, "Identifier", { fg = colors.base05 })
set(0, "Function", { fg = colors.base0D })
set(0, "Statement", { fg = colors.base0E })
set(0, "Operator", { fg = colors.base0C })
set(0, "Keyword", { fg = colors.base0E })
set(0, "Type", { fg = colors.base0A })
set(0, "Structure", { fg = colors.base0A })
set(0, "StorageClass", { fg = colors.base0E })
set(0, "PreProc", { fg = colors.base0C })
set(0, "Include", { fg = colors.base0E })
set(0, "Define", { fg = colors.base0E })
set(0, "Macro", { fg = colors.base0C })
set(0, "PreCondit", { fg = colors.base0C })
set(0, "Conditional", { fg = colors.base0E })
set(0, "Repeat", { fg = colors.base0E })
set(0, "Label", { fg = colors.base0A })
set(0, "Special", { fg = colors.base0C })
set(0, "Delimiter", { fg = colors.base05 })
set(0, "Underlined", { underline = true })
set(0, "Bold", { bold = true })
set(0, "Italic", { italic = true })
set(0, "Error", { fg = colors.base08, bg = colors.base00 })

-- Treesitter and semantic tokens
set(0, "@comment", { link = "Comment" })
set(0, "@comment.todo", { fg = colors.base0A, bg = colors.base01, bold = true })
set(0, "@comment.error", { fg = colors.base08 })
set(0, "@punctuation", { link = "Delimiter" })
set(0, "@punctuation.bracket", { link = "Delimiter" })
set(0, "@punctuation.special", { fg = colors.base0C })
set(0, "@string", { link = "String" })
set(0, "@string.regex", { fg = colors.base0C })
set(0, "@string.escape", { fg = colors.base0C })
set(0, "@character", { link = "Character" })
set(0, "@character.special", { fg = colors.base0C })
set(0, "@number", { link = "Number" })
set(0, "@number.float", { link = "Float" })
set(0, "@float", { link = "Float" })
set(0, "@boolean", { link = "Boolean" })
set(0, "@constant", { link = "Constant" })
set(0, "@constant.builtin", { fg = colors.base09 })
set(0, "@constant.macro", { fg = colors.base0C })
set(0, "@type", { link = "Type" })
set(0, "@type.builtin", { fg = colors.base0A })
set(0, "@type.definition", { fg = colors.base0A, bold = true })
set(0, "@type.qualifier", { fg = colors.base0E })
set(0, "@attribute", { fg = colors.base0C })
set(0, "@variable", { fg = colors.base05 })
set(0, "@variable.builtin", { fg = colors.base09 })
set(0, "@variable.parameter", { fg = colors.base05, italic = true })
set(0, "@variable.jai", { link = "@variable" })
set(0, "@field", { fg = colors.base05 })
set(0, "@property", { fg = colors.base05 })
set(0, "@parameter", { fg = colors.base05, italic = true })
set(0, "@parameter.reference", { fg = colors.base05 })
set(0, "@function", { link = "Function" })
set(0, "@function.call", { fg = colors.base0D })
set(0, "@function.definition", { fg = colors.base0D, bold = true })
set(0, "@function.builtin", { fg = colors.base0D })
set(0, "@function.macro", { fg = colors.base0C })
set(0, "@method", { link = "Function" })
set(0, "@module", { fg = colors.base0C })
set(0, "@constructor", { fg = colors.base0A })
set(0, "@keyword", { link = "Keyword" })
set(0, "@keyword.function", { fg = colors.base0E })
set(0, "@keyword.operator", { fg = colors.base0E })
set(0, "@keyword.return", { fg = colors.base0E, bold = true })
set(0, "@keyword.conditional", { link = "Keyword" })
set(0, "@keyword.repeat", { link = "Keyword" })
set(0, "@keyword.import", { fg = colors.base0E })
set(0, "@keyword.directive", { fg = colors.base0C })
set(0, "@keyword.modifier", { fg = colors.base0E })
set(0, "@operator", { link = "Operator" })
set(0, "@tag", { fg = colors.base0A })
set(0, "@tag.attribute", { fg = colors.base0C })
set(0, "@tag.delimiter", { fg = colors.base05 })

-- Jai-specific
set(0, "@keyword.jai", { fg = colors.base0E })
set(0, "@storageclass.jai", { fg = colors.base0E })
set(0, "@function.jai", { fg = colors.base0D })
set(0, "@function.call.jai", { fg = colors.base0D })
set(0, "@operator.jai", { fg = colors.base0C })
set(0, "@punctuation.special.jai", { fg = colors.base0C })
set(0, "@punctuation.delimiter.jai", { fg = colors.base05 })
set(0, "@variable.builtin.jai", { fg = colors.base09 })
set(0, "@constant.builtin.jai", { fg = colors.base09 })

-- LSP
set(0, "LspReferenceText", { bg = colors.base02 })
set(0, "LspReferenceRead", { bg = colors.base02 })
set(0, "LspReferenceWrite", { bg = colors.base02 })
set(0, "LspSignatureActiveParameter", { fg = colors.base05, bg = colors.base01, bold = true })
set(0, "LspInlayHint", { fg = colors.base03, bg = colors.base01 })
set(0, "LspCodeLens", { fg = colors.base03 })
set(0, "LspCodeLensSeparator", { fg = colors.base03 })

-- Diagnostics
set(0, "DiagnosticError", { fg = colors.base08 })
set(0, "DiagnosticWarn", { fg = colors.base09 })
set(0, "DiagnosticInfo", { fg = colors.base0D })
set(0, "DiagnosticHint", { fg = colors.base0C })
set(0, "DiagnosticOk", { fg = colors.base0B })
set(0, "DiagnosticVirtualTextError", { fg = colors.base08, bg = colors.base01 })
set(0, "DiagnosticVirtualTextWarn", { fg = colors.base09, bg = colors.base01 })
set(0, "DiagnosticVirtualTextInfo", { fg = colors.base0D, bg = colors.base01 })
set(0, "DiagnosticVirtualTextHint", { fg = colors.base0C, bg = colors.base01 })
set(0, "DiagnosticVirtualTextOk", { fg = colors.base0B, bg = colors.base01 })
set(0, "DiagnosticUnderlineError", { undercurl = true, sp = colors.base08 })
set(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = colors.base09 })
set(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = colors.base0D })
set(0, "DiagnosticUnderlineHint", { undercurl = true, sp = colors.base0C })
set(0, "DiagnosticUnderlineOk", { undercurl = true, sp = colors.base0B })
set(0, "DiagnosticSignError", { fg = colors.base08, bg = colors.base00 })
set(0, "DiagnosticSignWarn", { fg = colors.base09, bg = colors.base00 })
set(0, "DiagnosticSignInfo", { fg = colors.base0D, bg = colors.base00 })
set(0, "DiagnosticSignHint", { fg = colors.base0C, bg = colors.base00 })
set(0, "DiagnosticSignOk", { fg = colors.base0B, bg = colors.base00 })

-- Diff & Git
set(0, "DiffAdd", { fg = colors.base0B, bg = colors.base01 })
set(0, "DiffDelete", { fg = colors.base08, bg = colors.base01 })
set(0, "DiffChange", { fg = colors.base0A, bg = colors.base01 })
set(0, "DiffText", { fg = colors.base00, bg = colors.base0A })
set(0, "DiffAdded", { fg = colors.base0B })
set(0, "DiffRemoved", { fg = colors.base08 })
set(0, "DiffChanged", { fg = colors.base0A })
set(0, "GitSignsAdd", { fg = colors.base0B })
set(0, "GitSignsChange", { fg = colors.base0A })
set(0, "GitSignsDelete", { fg = colors.base08 })
set(0, "GitSignsCurrentLineBlame", { fg = colors.base03 })

-- Spell checking
set(0, "SpellBad", { undercurl = true, sp = colors.base08 })
set(0, "SpellCap", { undercurl = true, sp = colors.base0A })
set(0, "SpellLocal", { undercurl = true, sp = colors.base0C })
set(0, "SpellRare", { undercurl = true, sp = colors.base0E })

-- Telescope
set(0, "TelescopeNormal", { fg = colors.base05, bg = colors.base00 })
set(0, "TelescopeBorder", { fg = colors.base01, bg = colors.base00 })
set(0, "TelescopeSelection", { fg = colors.base00, bg = colors.base0D, bold = true })
set(0, "TelescopeSelectionCaret", { fg = colors.base08, bg = colors.base0D, bold = true })
set(0, "TelescopeMultiSelection", { fg = colors.base00, bg = colors.base0B })
set(0, "TelescopeMatching", { fg = colors.base0A })
set(0, "TelescopeTitle", { fg = colors.base0D })

-- Trouble
set(0, "TroubleNormal", { fg = colors.base05, bg = colors.base01 })
set(0, "TroubleNormalNC", { fg = colors.base05, bg = colors.base01 })
set(0, "TroubleFoldIcon", { fg = colors.base03 })
set(0, "TroubleIndent", { fg = colors.base02 })
set(0, "TroubleText", { fg = colors.base05 })
set(0, "TroubleCount", { fg = colors.base0A })
set(0, "TroubleFile", { fg = colors.base05 })
set(0, "TroubleLocation", { fg = colors.base03 })
set(0, "TroublePreview", { fg = colors.base05, bg = colors.base01 })

-- Which-key & cmp UI helpers
set(0, "WhichKey", { fg = colors.base0D })
set(0, "WhichKeyGroup", { fg = colors.base0A })
set(0, "WhichKeyDesc", { fg = colors.base05 })
set(0, "WhichKeySeparator", { fg = colors.base03 })
set(0, "WhichKeyFloat", { bg = colors.base01 })
set(0, "CmpItemAbbr", { fg = colors.base05 })
set(0, "CmpItemAbbrMatch", { fg = colors.base0A })
set(0, "CmpItemAbbrMatchFuzzy", { fg = colors.base0A })
set(0, "CmpItemMenu", { fg = colors.base03 })
set(0, "CmpItemKind", { fg = colors.base0D })
set(0, "CmpItemKindFunction", { fg = colors.base0D })
set(0, "CmpItemKindMethod", { fg = colors.base0D })
set(0, "CmpItemKindVariable", { fg = colors.base05 })
set(0, "CmpItemKindField", { fg = colors.base05 })
set(0, "CmpItemKindProperty", { fg = colors.base05 })
set(0, "CmpItemKindValue", { fg = colors.base09 })
set(0, "CmpItemKindEnum", { fg = colors.base0A })
set(0, "CmpItemKindEnumMember", { fg = colors.base0A })
set(0, "CmpItemKindKeyword", { fg = colors.base0E })
set(0, "CmpItemKindText", { fg = colors.base03 })
set(0, "CmpItemKindClass", { fg = colors.base0A })
set(0, "CmpItemKindInterface", { fg = colors.base0A })
set(0, "CmpItemKindModule", { fg = colors.base0C })
set(0, "CmpItemKindSnippet", { fg = colors.base0C })
set(0, "CmpItemKindColor", { fg = colors.base0A })
set(0, "CmpItemKindFile", { fg = colors.base05 })
set(0, "CmpItemKindFolder", { fg = colors.base0D })
set(0, "CmpItemKindReference", { fg = colors.base0C })

-- Indent guides
set(0, "IndentBlanklineChar", { fg = colors.base02 })
set(0, "IndentBlanklineContextChar", { fg = colors.base03 })
set(0, "IblIndent", { fg = colors.base02 })
set(0, "IblWhitespace", { fg = colors.base02 })
set(0, "IblScope", { fg = colors.base03 })

-- Illuminated word / references
set(0, "IlluminatedWordText", { bg = colors.base02 })
set(0, "IlluminatedWordRead", { bg = colors.base02 })
set(0, "IlluminatedWordWrite", { bg = colors.base02 })

-- Lazy.nvim interface
set(0, "LazyNormal", { fg = colors.base05, bg = colors.base01 })
set(0, "LazyBorder", { fg = colors.base03, bg = colors.base01 })
set(0, "LazyTitle", { fg = colors.base0D, bg = colors.base01 })
set(0, "LazyButton", { fg = colors.base05, bg = colors.base01 })
set(0, "LazyButtonActive", { fg = colors.base00, bg = colors.base0D })
set(0, "LazyH1", { fg = colors.base0D })
set(0, "LazyH2", { fg = colors.base0C })
set(0, "LazyComment", { fg = colors.base03 })
set(0, "LazyCommit", { fg = colors.base0B })
set(0, "LazyCommitIssue", { fg = colors.base08 })
set(0, "LazyCommitScope", { fg = colors.base0D })
set(0, "LazyCommitType", { fg = colors.base0A })
set(0, "LazyDimmed", { fg = colors.base03 })
set(0, "LazyDir", { fg = colors.base0C })
set(0, "LazyProgressDone", { fg = colors.base0B })
set(0, "LazyProgressTodo", { fg = colors.base03 })
set(0, "LazyProp", { fg = colors.base0C })
set(0, "LazyReasonCmd", { fg = colors.base09 })
set(0, "LazyReasonEvent", { fg = colors.base0A })
set(0, "LazyReasonFt", { fg = colors.base0E })
set(0, "LazyReasonImport", { fg = colors.base0C })
set(0, "LazyReasonKeys", { fg = colors.base0D })
set(0, "LazyReasonPlugin", { fg = colors.base0B })
set(0, "LazyReasonRuntime", { fg = colors.base0C })
set(0, "LazyReasonSource", { fg = colors.base08 })
set(0, "LazyReasonStart", { fg = colors.base0D })
set(0, "LazySpecial", { fg = colors.base0C })
set(0, "LazyTaskError", { fg = colors.base08 })
set(0, "LazyTaskOutput", { fg = colors.base05 })
set(0, "LazyUrl", { fg = colors.base0C })
set(0, "LazyValue", { fg = colors.base09 })

-- NetRW
set(0, "netrwCursorLine", { bg = colors.base01 })
set(0, "netrwDir", { fg = colors.base0D })
set(0, "netrwExe", { fg = colors.base0B })

return colors
